function frect_4 = rectpulse_4(x)
%RECTPULSE_4
%    FRECT_4 = RECTPULSE_4(X)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    28-May-2021 14:44:31

frect_4 = rectangularPulse(0.0,2.0,x);
