function frect_3 = rectpulse_3(x)
%RECTPULSE_3
%    FRECT_3 = RECTPULSE_3(X)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    28-May-2021 14:32:02

frect_3 = rectangularPulse(0.0,1.0,x);
