function f = rectpulse_1(x)
%RECTPULSE_1
%    F = RECTPULSE_1(X)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Apr-2021 15:32:58

f = rectangularPulse(-1.0,1.0,x);
