function frect_2 = rectpulse_2(x)
%RECTPULSE_2
%    FRECT_2 = RECTPULSE_2(X)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    28-May-2021 14:28:00

frect_2 = rectangularPulse(-1.0,1.0,x)./2.0;
