function ftri_4 = tripulse_4(x)
%TRIPULSE_4
%    FTRI_4 = TRIPULSE_4(X)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Apr-2021 09:12:53

t2 = x./2.0;
ftri_4 = -(t2-1.0./2.0).*rectangularPulse(0.0,1.0,-t2+1.0./2.0);
