function ftri_2 = tripulse_2(x)
%TRIPULSE_2
%    FTRI_2 = TRIPULSE_2(X)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Apr-2021 10:09:14

ftri_2 = (x./2.0+1.0).*rectangularPulse(-2.0,0.0,x);
