function ftri = tripulse_1(x)
%TRIPULSE_1
%    FTRI = TRIPULSE_1(X)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Apr-2021 15:34:21

ftri = triangularPulse(-1.0,0.0,1.0,x);
